# Site settings
title: Sofia Cepeda
description: Modern-Blog A Elegant template for Jekyll
keywords: Modern, Blogging, Fun
author: Sofia Cepeda
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
